# kind: ImageStream
# apiVersion: image.openshift.io/v1
# metadata:
#     name: bc-emli-pin-mgmt-fe
#     namespace: default

apiVersion: tekton.dev/v1beta1 

kind: Pipeline 

metadata:

  name: qotd-build-and-deploy 

spec: 

  workspaces: 

  - name: shared-workspace

  params: 

  - name: git-url

    type: string

    description: url of the git repo for the code of deployment

    default: https://github.com/emilymendelson/bc-emli-pin-mgmt-fe-test.git

  - name: IMAGE

    type: string

    description: image to be built from the code

    default: image-registry.openshift-image-registry.svc:5000/<<project_name>>/qotd:latest

  tasks: 

  - name: fetch-repository

    taskRef:

      name: git-clone

      kind: ClusterTask

    workspaces:

    - name: output

      workspace: shared-workspace

    params:

    - name: url

      value: $(params.git-url)

    - name: subdirectory

      value: ""

    - name: deleteExisting

      value: "true"

  - name: build-image 

    taskRef:

      name: buildah

      kind: ClusterTask

    params:

    - name: TLSVERIFY

      value: "false"

    - name: IMAGE

      value: $(params.IMAGE)

    workspaces:

    - name: source

      workspace: shared-workspace

    runAfter:

    - fetch-repository

  - name: apply-manifests 

    taskRef:

      name: apply-manifests

    workspaces:

    - name: source

      workspace: shared-workspace

    runAfter: 

    - build-image